### ISSUE TITLE
install with tensorflow 2.12 instead of tensorflow-gpu

### ISSUE THREAD

**Issue by rshiroko** [Gaius-Augustus/learnMSA#1]
Hello!
I am setting up learnMSA with the current tensorflow. It works on multiple (16) CPUs, but the calculation runs out of the 3-day time limit. The GPU variant with tensorflow 2.12 errs (see attached).  Install instructions for learnMSA refer to tensorflow-gpu. However, as of December 2022, tensorflow-gpu has been removed and has been replaced with tensorflow.  Please confirm that learMSA should work with tensorflow 2.12. 

[learnMSAGPU_out.txt](https://github.com/Gaius-Augustus/learnMSA/files/11081125/learnMSAGPU_out.txt)

**Comment by felbecker** [comment]
Hi!

I reproduced the error with TF 2.12. I will push a fix as soon as possible. Sorry that you ran into this and thanks for reporting.

Can you downgrade TF until then? 2.5.0 should work.

From your output it looks like the sequences are rather long. I am not surprised that running on CPU is not feasible in that case.

**Comment by rshiroko** [comment]
I tried pip install tensorflow-gpu==2.5.*
After that, pip install learnMSA gives several dependency conflicts. See attached.
[learnMSA install with tensorflow-gpu2-5.txt](https://github.com/Gaius-Augustus/learnMSA/files/11083640/learnMSA.install.with.tensorflow-gpu2-5.txt)

**Comment by rshiroko** [comment]
Thank you!
Yes, that (base) was from the cluster's environment. I did not think it through.
Not all speak python and have root...
