### ISSUE TITLE
An option for keeping the header of each sequence in the aligned fasta.

### ISSUE THREAD

**Issue by permia** [Gaius-Augustus/learnMSA#15]
The sequences that we downloaded from NCBI usually are in FASTA format. e.g.

```
>QEG08237.1 MAG: ORF1b polyprotein [Pacific salmon nidovirus]
MCGVFLSANGKLVARVDKSIRSVDVNITKGDGSRVSFIGTCKKSNTIQMDTGHGRSILKMSLKSEDAIER...
```
```
>seqID seq_description [organism]
```
learnMSA would only keep the seqID in the results, which are inconvenient in some situation where I want to see the seq_description.

**Comment by felbecker** [comment]
Fixed in 2.0.9.
Now learnMSA correctly outputs the full headers.

Thanks for reporting.
